engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - index.js
exclude_paths:
- "dist/"
- "test/"
- "frontexpress-path-to-regexp.js"
- "frontexpress-path-to-regexp.min.js"